project:
  type: book

book:
  title: "World-Manual"
  author: "陈照然"
  date: "1/15/2026"
  cover-image: cover.jpg
  sidebar:
    logo: cover.jpg

  chapters:
    - index.qmd
    - part: "世界观设定"
      chapters:
        - background.qmd
        - design.qmd
    - part: "系统与技术"
      chapters:
        - energy.qmd
        - tech.qmd
    - part: "环境与社会"
      chapters:
        - environment.qmd
        - social.qmd
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    toc: true
    toc-depth: 3
    toc-location: right
  pdf:
    toc: true
    documentclass: scrreprt



