project:
  type: book

lang: zh-Hans

book:
  title: "World-Manual"
  author: "陈照然 郭佳琪 姚雨佳 郑融生 虞凯程 蒋浩翔 陈灵石"
  date: "1/15/2026"
  cover-image: cover.jpg
  sidebar:
    logo: cover.jpg

  chapters:
    - index.qmd
    - part: "世界观设定"
      chapters:
        - background.qmd
        - design.qmd
    - part: "系统与技术"
      chapters:
        - energy.qmd
        - tech.qmd
    - part: "环境与社会"
      chapters:
        - environment.qmd
        - social.qmd

  appendices: 
    - mazu.qmd
    - jiyinchongzu.qmd
    - dameiyunnan.qmd
    - immigration.qmd
    - tenmillion.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    toc: true
    toc-depth: 5
    toc-location: right
  pdf:
    toc: true
    documentclass: scrreprt
    links-as-notes: true
    pdf-engine: xelatex
    include-in-header:
      - text: |
          \usepackage{pdfpages}
